# Generated by Django 5.0.7 on 2024-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complete_name', models.CharField(default='', max_length=100)),
                ('dni', models.CharField(default='', max_length=8)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('problem', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
