# Generated by Django 5.0.8 on 2024-08-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_user_username_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
